### PR TITLE
Implement ability to add error comments to PRs

### PR DESCRIPTION
**Pull request by JohnathonBowers**
## Description

These changes provide the initial implementation of the ability for error messages to be added as comments to PRs. The logic for parsing changelog entries has been nested within a `try-catch` block. Any errors thrown during the parsing of the "Changelog" section of the PR description — which are the errors the contributor should know about and can fix — are passed as arguments to the `postPRComment` function in `githubUtils.js`. This function uses a map of error constructors and generator functions to derive the proper message to add as a PR comment.

In order to manually test this feature, I believe we would need to merge the code into `main`. However, I wanted to hold off on doing that so that @BigSamu can take a look at the general setup before we move to manual testing.

## Issues

Addresses Issue #2

### CODE REVIEW

**Comment by BigSamu** [comment]
@JohnathonBowers,

Let's take a look for this after solving my comments for PR #10. With that code more modularized we can get back to this.

**Comment by JohnathonBowers** [comment]
@BigSamu , I finished modularizing the code in `index.js` and implementing the PR comment feature. Let me know your thoughts!

**Review by BigSamu — COMMENTED** [review]
I just deleted these files in your branch. They are not required any more. The main branch don't have this files either (I removed them this morning)

**Comment by JohnathonBowers** [comment]
> I just deleted files [fetchData.js, apiModule.js, and fetchData.test.js](https://github.com/BigSamu/OpenSearch_Change_Set_Create_Action/pull/11/commits/9f7d81bb4356c814752500399617af2d9db3b13d) in your branch. They are not required any more. The main branch don't have this files either (I removed them this morning)

Sounds good. Thank you!

**Pull request merged**
